#!/usr/bin/env Rscript
###############################################################################
##  build_app.R  -  generate the deployable single-file app from the package
##
##  The package in R/ is the single source of truth. This script concatenates
##  those files, in dependency order, into one self-contained app/app.R, which
##  is what shinylive::export() compiles for the browser build.
##
##  Never edit app/app.R by hand: it is overwritten every time this runs.
##
##  Usage, from the package root:
##      Rscript build_app.R
##  or, in RStudio:
##      source("build_app.R")
###############################################################################

## Dependency order. constants.R must come first (it defines DESIGNS, the
## helpers and the credits); the UI and server come last.
ORDER <- c(
  "constants.R",       # constants, credits, logo, DESIGNS, helpers, demo_data
  "analyze.R",         # the analysis engine
  "assumptions.R",     # assumption tests and transformations (defines TRANS)
  "tables_detail.R",   # integrated tables of means
  "posthoc.R",         # post-hoc procedures
  "plots.R",           # plots
  "interpret.R",       # plain-English interpretation and the report CSS
  "tables_sketch.R",   # the tables of means shown in the app
  "report.R",          # the HTML report
  "run_all.R",         # the multi-response driver and the help text
  "app_ui.R",          # the user interface
  "app_server.R"       # the server logic
)
## run_app.R is deliberately left out: it holds run_DOEpro(), the package
## launcher. The single-file app calls shinyApp() directly instead (added below).

root    <- getwd()
r_dir   <- file.path(root, "R")
out_dir <- file.path(root, "app")
out     <- file.path(out_dir, "app.R")

stopifnot(dir.exists(r_dir))
missing <- setdiff(ORDER, list.files(r_dir))
if (length(missing))
  stop("Missing from R/: ", paste(missing, collapse = ", "), call. = FALSE)

## Any R/ file not named in ORDER (other than the launcher) would be silently
## dropped from the app, so refuse to build rather than ship a broken file.
extra <- setdiff(list.files(r_dir, pattern = "\\.R$"), c(ORDER, "run_app.R"))
if (length(extra))
  stop("R/ has files that build_app.R does not know where to place: ",
       paste(extra, collapse = ", "),
       "\nAdd them to ORDER in build_app.R.", call. = FALSE)

version <- read.dcf("DESCRIPTION", "Version")[1, 1]

header <- c(
  "###############################################################################",
  "##  DOEpro - analysis of designed agricultural experiments",
  "##",
  "##  DO NOT EDIT THIS FILE BY HAND.",
  "##  It is generated from the package sources in R/ by build_app.R, and is",
  "##  overwritten every time that script runs. Edit the files in R/ instead.",
  "##",
  sprintf("##  Generated: %s from DOEpro %s",
          format(Sys.Date(), "%d %B %Y"), version),
  "##  Source:    https://github.com/Uzairkhan11w/DOEpro",
  "##  Run with:  shiny::runApp(\"app.R\")",
  "###############################################################################",
  "",
  "## The single-file build attaches its packages directly; the package build",
  "## declares them in DESCRIPTION and NAMESPACE instead.",
  ".pkgs <- c(\"shiny\", \"DT\", \"ggplot2\")",
  ".missing <- .pkgs[!vapply(.pkgs, requireNamespace, logical(1), quietly = TRUE)]",
  "if (length(.missing)) {",
  "  stop(\"Missing packages. Please run:\\n  install.packages(c(\",",
  "       paste0('\"', .missing, '\"', collapse = \", \"), \"))\", call. = FALSE)",
  "}",
  "library(shiny)",
  "library(DT)",
  "library(ggplot2)",
  ""
)

body <- unlist(lapply(ORDER, function(f) {
  txt <- readLines(file.path(r_dir, f), warn = FALSE)

  ## Drop only the roxygen "_PACKAGE" marker, which means nothing outside a
  ## package. Everything else is copied verbatim: the roxygen comments are
  ## harmless here, and utils::globalVariables() is a silent no-op in a script,
  ## so there is no reason to risk mangling the source by rewriting it.
  txt <- txt[!grepl('^\\s*"_PACKAGE"\\s*$', txt)]

  c(sprintf("## ---------------------------------------------------------- %s ----", f),
    txt, "")
}))

## how many source expressions the "_PACKAGE" marker accounted for
n_stripped <- sum(vapply(ORDER, function(f)
  sum(grepl('^\\s*"_PACKAGE"\\s*$', readLines(file.path(r_dir, f), warn = FALSE))),
  integer(1)))

footer <- c(
  "###############################################################################",
  "##  LAUNCH",
  "###############################################################################",
  "shinyApp(doepro_ui(), doepro_server)",
  ""
)

if (!dir.exists(out_dir)) dir.create(out_dir, recursive = TRUE)
writeLines(c(header, body, footer), out)

## ------------------------------------------------------------- verify ------
## The generated file must parse, and it must contain every expression from the
## sources it was built from. Counting them catches a copy that silently loses
## code, which is far more dangerous than a build that simply fails.
gen <- tryCatch(parse(out), error = function(e)
  stop("The generated app.R does not parse: ", conditionMessage(e), call. = FALSE))

src_n    <- sum(vapply(ORDER, function(f) length(parse(file.path(r_dir, f))), integer(1)))
head_n   <- length(parse(text = paste(header, collapse = "\n")))
foot_n   <- length(parse(text = paste(footer, collapse = "\n")))
expected <- src_n - n_stripped + head_n + foot_n

if (length(gen) != expected)
  stop(sprintf(paste("The generated app.R has %d expressions but %d were expected",
                     "(%d from R/, less %d stripped, plus %d header and %d footer).",
                     "Code was lost or duplicated - refusing to ship a broken app."),
               length(gen), expected, src_n, n_stripped, head_n, foot_n), call. = FALSE)

n <- length(readLines(out))
message(sprintf("Wrote %s", out))
message(sprintf("  %d lines, %.0f KB, %d expressions from %d source files - verified complete.",
                n, file.size(out) / 1024, length(gen), length(ORDER)))
message("Next: unlink(\"docs\", recursive = TRUE); shinylive::export(\"app\", \"docs\")")
