#!/usr/bin/env Rscript
###############################################################################
##  build_app.R  -  generate the deployable single-file app from the package
##
##  The package in R/ is the single source of truth. This script concatenates
##  those files, in dependency order, into one self-contained app/app.R, which
##  is what shinylive::export() compiles for the browser build.
##
##  Never edit app/app.R by hand: it is overwritten every time this runs.
##
##  Usage, from the package root:
##      Rscript build_app.R
##  or, in RStudio:
##      source("build_app.R")
##  and then, to compile the browser build into docs/:
##      export_app()
##
##  export_app() runs shinylive::export() and then adds the StatLabX loading
##  screen from site/. The export rewrites docs/ from scratch, so the loading
##  screen has to be added again after every export; build docs/ only this way.
###############################################################################

## Dependency order. constants.R must come first (it defines DESIGNS, the
## helpers and the credits); the UI and server come last.
ORDER <- c(
  "constants.R",       # constants, credits, logo, DESIGNS, helpers, demo_data
  "data_quality.R",    # checks and corrections run on the data when it is loaded
  "analyze.R",         # the analysis engine
  "assumptions.R",     # assumption tests and transformations (defines TRANS)
  "tables_detail.R",   # integrated tables of means
  "posthoc.R",         # post-hoc procedures
  "dunnett.R",         # Dunnett's test against a control
  "plots.R",           # plots
  "descriptives.R",    # descriptive statistics and distribution plots
  "correlation.R",     # correlation between pairs of variables
  "regression.R",      # simple and multiple linear regression
  "pca.R",             # principal component analysis
  "cluster.R",         # hierarchical cluster analysis
  "factor.R",          # factor analysis
  "interpret.R",       # plain-English interpretation and the report CSS
  "readings.R",        # readings after the ANOVA tables and plots
  "tables_sketch.R",   # the tables of means shown in the app
  "report.R",          # the HTML report
  "run_all.R",         # the multi-response driver and the help text
  "app_ui.R",          # the user interface
  "app_server.R"       # the server logic
)
## run_app.R is deliberately left out: it holds run_DOEpro(), the package
## launcher. The single-file app calls shinyApp() directly instead (added below).

root    <- getwd()
r_dir   <- file.path(root, "R")
out_dir <- file.path(root, "app")
out     <- file.path(out_dir, "app.R")

stopifnot(dir.exists(r_dir))
missing <- setdiff(ORDER, list.files(r_dir))
if (length(missing))
  stop("Missing from R/: ", paste(missing, collapse = ", "), call. = FALSE)

## Any R/ file not named in ORDER (other than the launcher) would be silently
## dropped from the app, so refuse to build rather than ship a broken file.
extra <- setdiff(list.files(r_dir, pattern = "\\.R$"), c(ORDER, "run_app.R"))
if (length(extra))
  stop("R/ has files that build_app.R does not know where to place: ",
       paste(extra, collapse = ", "),
       "\nAdd them to ORDER in build_app.R.", call. = FALSE)

version <- read.dcf("DESCRIPTION", "Version")[1, 1]

header <- c(
  "###############################################################################",
  "##  DOEpro - analysis of designed agricultural experiments",
  "##",
  "##  DO NOT EDIT THIS FILE BY HAND.",
  "##  It is generated from the package sources in R/ by build_app.R, and is",
  "##  overwritten every time that script runs. Edit the files in R/ instead.",
  "##",
  sprintf("##  Generated: %s from DOEpro %s",
          format(Sys.Date(), "%d %B %Y"), version),
  "##  Source:    https://github.com/Uzairkhan11w/DOEpro",
  "##  Run with:  shiny::runApp(\"app.R\")",
  "###############################################################################",
  "",
  "## The single-file build attaches its packages directly; the package build",
  "## declares them in DESCRIPTION and NAMESPACE instead.",
  ".pkgs <- c(\"shiny\", \"DT\", \"ggplot2\")",
  ".missing <- .pkgs[!vapply(.pkgs, requireNamespace, logical(1), quietly = TRUE)]",
  "if (length(.missing)) {",
  "  stop(\"Missing packages. Please run:\\n  install.packages(c(\",",
  "       paste0('\"', .missing, '\"', collapse = \", \"), \"))\", call. = FALSE)",
  "}",
  "library(shiny)",
  "library(DT)",
  "library(ggplot2)",
  ""
)

body <- unlist(lapply(ORDER, function(f) {
  txt <- readLines(file.path(r_dir, f), warn = FALSE)

  ## Drop only the roxygen "_PACKAGE" marker, which means nothing outside a
  ## package. Everything else is copied verbatim: the roxygen comments are
  ## harmless here, and utils::globalVariables() is a silent no-op in a script,
  ## so there is no reason to risk mangling the source by rewriting it.
  txt <- txt[!grepl('^\\s*"_PACKAGE"\\s*$', txt)]

  c(sprintf("## ---------------------------------------------------------- %s ----", f),
    txt, "")
}))

## how many source expressions the "_PACKAGE" marker accounted for
n_stripped <- sum(vapply(ORDER, function(f)
  sum(grepl('^\\s*"_PACKAGE"\\s*$', readLines(file.path(r_dir, f), warn = FALSE))),
  integer(1)))

footer <- c(
  "###############################################################################",
  "##  LAUNCH",
  "###############################################################################",
  "shinyApp(doepro_ui(), doepro_server)",
  ""
)

if (!dir.exists(out_dir)) dir.create(out_dir, recursive = TRUE)
writeLines(c(header, body, footer), out)

## ------------------------------------------------------------- verify ------
## The generated file must parse, and it must contain every expression from the
## sources it was built from. Counting them catches a copy that silently loses
## code, which is far more dangerous than a build that simply fails.
gen <- tryCatch(parse(out), error = function(e)
  stop("The generated app.R does not parse: ", conditionMessage(e), call. = FALSE))

src_n    <- sum(vapply(ORDER, function(f) length(parse(file.path(r_dir, f))), integer(1)))
head_n   <- length(parse(text = paste(header, collapse = "\n")))
foot_n   <- length(parse(text = paste(footer, collapse = "\n")))
expected <- src_n - n_stripped + head_n + foot_n

if (length(gen) != expected)
  stop(sprintf(paste("The generated app.R has %d expressions but %d were expected",
                     "(%d from R/, less %d stripped, plus %d header and %d footer).",
                     "Code was lost or duplicated - refusing to ship a broken app."),
               length(gen), expected, src_n, n_stripped, head_n, foot_n), call. = FALSE)

n <- length(readLines(out))
message(sprintf("Wrote %s", out))
message(sprintf("  %d lines, %.0f KB, %d expressions from %d source files - verified complete.",
                n, file.size(out) / 1024, length(gen), length(ORDER)))
message("Next, for the browser build: export_app()")

## ------------------------------------------------------ the browser build ---
## shinylive::export() compiles app/ into docs/, writing every file afresh,
## including index.html and its service worker. The StatLabX loading screen
## (site/) replaces shinylive's unexplained spinner, so it is put back after
## every export here rather than by hand.
export_app <- function(app = "app", out = "docs") {
  unlink(out, recursive = TRUE)
  shinylive::export(app, out)
  brand_site(out)
  invisible(out)
}

## The loading screen: a branded page shown until Shiny connects, with the
## real progress of the download of R and its packages. The files the first
## visit downloads are listed here with their sizes in this build, so the
## bar measures the bytes received against the true total. If shinylive
## changes the files it writes, this stops rather than ship a wrong total
## or an unbranded page.
brand_site <- function(out = "docs", site = "site") {
  index <- file.path(out, "index.html")
  sw <- file.path(out, "shinylive-sw.js")
  stopifnot(file.exists(index), file.exists(sw), dir.exists(site))
  html <- paste(readLines(index, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
  if (grepl("slx-loading", html, fixed = TRUE))
    stop(index, " already has the loading screen; run export_app() for a fresh export.", call. = FALSE)
  read <- function(f) paste(readLines(file.path(site, f), warn = FALSE, encoding = "UTF-8"), collapse = "\n")

  ## what the first visit downloads: R and its built-in library, the
  ## package list and every package, and R's other libraries
  webr <- file.path(out, "shinylive", "webr")
  core <- file.path(webr, c("webr-worker.js", "R.js", "R.wasm", "libRblas.so", "libRlapack.so",
                            "library.js.metadata", "library.data.gz"))
  pkgs <- list.files(file.path(webr, "packages"), "[.]tgz$", recursive = TRUE, full.names = TRUE)
  libs <- list.files(file.path(webr, "vfs", "usr", "lib", "R", "library"), "[.](data[.]gz|js[.]metadata)$",
                     full.names = TRUE)
  files <- c(core, file.path(webr, "packages", "metadata.rds"), pkgs, libs)
  gone <- files[!file.exists(files)]
  if (length(gone) || !length(pkgs))
    stop("The export no longer has the files the loading screen counts (", paste(basename(gone), collapse = ", "),
         "). Check what a first visit downloads and update brand_site().", call. = FALSE)
  rel <- substring(normalizePath(files, "/"), nchar(normalizePath(out, "/")) + 2)
  sizes <- sprintf('"%s": %.0f', rel, file.size(files))
  js <- sub("/*FILES*/{}", paste0("{", paste(sizes, collapse = ", "), "}"), read("loading.js"), fixed = TRUE)
  if (!grepl('"shinylive/webr/R.wasm"', js, fixed = TRUE))
    stop("site/loading.js lost its /*FILES*/{} placeholder.", call. = FALSE)

  ## the logo, as the page and the browser tab show it, taken from the
  ## package so that there is one copy
  src <- paste(readLines(file.path("R", "constants.R"), warn = FALSE), collapse = "\n")
  b64 <- regmatches(src, regexpr("LOGO_URI <- \"data:image/png;base64,[A-Za-z0-9+/=]+", src))
  if (!length(b64)) stop("LOGO_URI not found in R/constants.R.", call. = FALSE)
  png <- jsonlite::base64_dec(sub(".*base64,", "", b64))
  writeBin(png, file.path(out, "logo.png"))
  writeBin(png, file.path(out, "favicon.ico"))

  ## one insertion each, or nothing is written
  put <- function(x, pattern, with) {
    if (lengths(regmatches(x, gregexpr(pattern, x, fixed = TRUE))) != 1)
      stop("index.html from shinylive no longer has exactly one ", pattern, call. = FALSE)
    sub(pattern, with, x, fixed = TRUE)
  }
  head <- paste0(
    "<title>StatLabX - statistics for agricultural and allied research</title>\n",
    "    <meta name=\"description\" content=\"Free analysis of designed agricultural experiments and ",
    "of agricultural data: ANOVA, means and C.D., post-hoc tests, regression, correlation, principal ",
    "components, clustering and factor analysis. R runs in your browser.\" />\n",
    "    <link rel=\"icon\" type=\"image/png\" href=\"logo.png\" />\n",
    "    <style>\n", read("loading.css"), "\n    </style>")
  html <- put(html, "<title>Shiny App</title>", head)
  html <- put(html, "<body>", paste0("<body>\n", read("loading.html"), "\n<script>\n", js, "\n</script>"))
  writeLines(html, index, useBytes = TRUE)
  cat(read("sw-progress.js"), file = sw, sep = "\n", append = TRUE)
  message(sprintf("Added the loading screen to %s: %d files, %.1f MB on a first visit.",
                  out, length(files), sum(file.size(files)) / 1048576))
  invisible(out)
}
